title: Practice Git
author: Brooke Arnold
email: brookelyn-arnold@uiowa.edu
description: > # this means to ignore newlines until "baseurl:"
  This is my very cool description of what I am working on here.

# social links
github_username:  broarnold

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
